public class MySampleClass {
    // Method to calculate the sum of two integers
    public static Integer addIntegers(Integer a, Integer b) {
        return a + b;
    }
    //Bundle US-1
    //Bundle US-2 This is actual one
    // Method to check if a given string is emptafdsfay
    //Demo Setup
//Get the conflict
    public static Boolean isStringEmpty(String str) {
        return String.isBlank(str);
    }
}
